# YOLOX installation is separate from this
# Github Actions does not use Conda. It installs python version and opencv differently, and just uses pip requirements.txt

name: hydo-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - opencv
  - numpy
  - pip 
  - pip:
    - -r requirements.txt
