# followed directions from https://autobencoder.com/2020-08-24-conda-actions/
name: hypercycle tests
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
jobs:
    build-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.6
            # - name: Build and make OpenCV
            #  uses: Dovyski/setup-opencv-action@v1
            #  with:
            #      opencv-version: '4.5.0'
            - name: python is python3
              run: sudo apt install python-is-python3
            - name: Set up pip dependencies
              run: |
                  pip install -r requirements.txt
            - name: Install YOLOX
              run: |
                  git clone https://github.com/Megvii-BaseDetection/YOLOX.git
                  cd YOLOX
                  pip3 install -U pip && pip3 install -r requirements.txt
                  pip3 install -v -e . 
            - name: Run pytest
              run: |
                  cd computer_vision
                  python3 -m pytest .
