# followed directions from https://autobencoder.com/2020-08-24-conda-actions/
name: hypercycle tests
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
jobs:
    build-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-18.04]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.6
              uses: actions/setup-python@v2
              with:
                  python-version: 3.6
            - name: set up conda
              uses: s-weigand/setup-conda@v1
              with:
                  update-conda: true
                  python-version: 3.6
                  conda-channels: anaconda, conda-forge
            - name: Install Conda Dependencies
              run: |
                  conda env update --file environment.yaml --name base
            - name: Install YOLOX
              run: |
                  git clone https://github.com/Megvii-BaseDetection/YOLOX.git
                  cd YOLOX
                  pip3 install -U pip && pip3 install -r requirements.txt
                  pip3 install -v -e .  # or  python3 setup.py develop
            - name: Run pytest
              run: |
                  apt-get install python3-opencv
                  pip install opencv-python
                  pip install pytest
                  cd computer_vision
                  pytest
