# followed directions from https://autobencoder.com/2020-08-24-conda-actions/
name: velovision deploy tests
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
jobs:
    inference-loop:
        runs-on: self-hosted
        steps:
            - name: Set up pip dependencies
              run: |
                  pip3 install -r requirements.txt
            - name: Install YOLOX
              run: |
                  pip3 install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
                  git clone https://github.com/Megvii-BaseDetection/YOLOX.git
                  cd YOLOX
                  pip3 install -U pip && pip3 install -r requirements.txt
                  pip3 install -v -e . 
            - name: Run pytest
              run: |
                  cd computer_vision
                  python3 -m pytest test_vision_deploy.py
